<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8"/>
		<title><?= $title; ?></title>
		<link rel="stylesheet" type="text/css" href="/assets/css/app.css"/>
		<script type="text/javascript" src="/assets/js/vendor.js"></script>
		<script type="text/javascript" src="/assets/js/app.js"></script>
	</head>
	<body>
		<header>
			<h1><a href="/"><?= $title; ?></a></h1>
			<nav>
			<ul>
					<li><a href="/">Home</a></li>
				</ul>
				<ul>
					<li><a href="/about">About</a></li>
				</ul>
			</nav>
		</header>
		<main>
<?= $v->section('main'); ?>
		</main>
		<footer>
			<p>
				&copy; <?= date('Y'); ?> &ndash; <?= $title; ?>
			</p>
		</footer>
	</body>
</html>